from cubevis.colorizer.utils import get_colorizer
from cubevis.colorizer.colorizer import BaseColorizer
from cubevis.colorizer.fto import *
from cubevis.colorizer.fivebyfive import *
from cubevis.colorizer.sq1 import *
from cubevis.colorizer.megaminx import *
from cubevis.colorizer.pyraminx import *
from cubevis.colorizer.skewb import *
from cubevis.colorizer.threebythree import *
from cubevis.colorizer.twobytwo import *